# config_train.yaml

WORK:
  ROOT_PATH: "D:\\GitWork\\ants_and_bees\\"
              
DATA:
  RAW_PATH: "D:\\GitWork\\ants_and_bees\\raw\\"
  PROCESSED_PATH: "D:\\GitWork\\ants_and_bees\\processed\\"

TRAIN:
  BATCH_SIZE: 4
  NUM_WORKERS: 4
  NUM_EPOCHS: 25
  LEARNING_RATE: 0.001
  MOMENTUM: 0.9


