# config_train.yaml

WORK:
  ROOT_PATH: "/home/user/work/ants_and_bees/"
              
DATA:
  ROOT_PATH: "/home/user/work/ants_and_bees/raw/"
  PROCESSED_PATH: "/home/user/work/ants_and_bees/processed/"

DATASET:
  TRANSFORM_MEAN: [0.485, 0.456, 0.406]
  TRANSFORM_STD:  [0.229, 0.224, 0.225]

TRAIN:
  BATCH_SIZE: 4
  NUM_WORKERS: 4
  NUM_EPOCHS: 25
  LEARNING_RATE: 0.001
  MOMENTUM: 0.9


