# config_train.yaml

WORK:
  ROOT_PATH: "/home/user/work/ants_and_bees/"
              
DATA:
  ROOT_PATH: "/home/user/work/ants_and_bees/raw/"
  PROCESSED_PATH: "/home/user/work/ants_and_bees/processed/"

TRAIN:
  BATCH_SIZE: 4
  NUM_WORKERS: 4
  NUM_EPOCHS: 25
  LEARNING_RATE: 0.001
  MOMENTUM: 0.9


